//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsole.VelibSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibSOAP.IVelibIWService")]
    public interface IVelibIWService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibIWService/GetVilles", ReplyAction="http://tempuri.org/IVelibIWService/GetVillesResponse")]
        string[] GetVilles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibIWService/GetVilles", ReplyAction="http://tempuri.org/IVelibIWService/GetVillesResponse")]
        System.Threading.Tasks.Task<string[]> GetVillesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibIWService/GetStations", ReplyAction="http://tempuri.org/IVelibIWService/GetStationsResponse")]
        string[] GetStations(string ville);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibIWService/GetStations", ReplyAction="http://tempuri.org/IVelibIWService/GetStationsResponse")]
        System.Threading.Tasks.Task<string[]> GetStationsAsync(string ville);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibIWService/GetNbVelib", ReplyAction="http://tempuri.org/IVelibIWService/GetNbVelibResponse")]
        string GetNbVelib(string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibIWService/GetNbVelib", ReplyAction="http://tempuri.org/IVelibIWService/GetNbVelibResponse")]
        System.Threading.Tasks.Task<string> GetNbVelibAsync(string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibIWService/GetNbVelibInStations", ReplyAction="http://tempuri.org/IVelibIWService/GetNbVelibInStationsResponse")]
        string[] GetNbVelibInStations(string stationsName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibIWService/GetNbVelibInStations", ReplyAction="http://tempuri.org/IVelibIWService/GetNbVelibInStationsResponse")]
        System.Threading.Tasks.Task<string[]> GetNbVelibInStationsAsync(string stationsName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibIWServiceChannel : ClientConsole.VelibSOAP.IVelibIWService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibIWServiceClient : System.ServiceModel.ClientBase<ClientConsole.VelibSOAP.IVelibIWService>, ClientConsole.VelibSOAP.IVelibIWService {
        
        public VelibIWServiceClient() {
        }
        
        public VelibIWServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibIWServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibIWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibIWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetVilles() {
            return base.Channel.GetVilles();
        }
        
        public System.Threading.Tasks.Task<string[]> GetVillesAsync() {
            return base.Channel.GetVillesAsync();
        }
        
        public string[] GetStations(string ville) {
            return base.Channel.GetStations(ville);
        }
        
        public System.Threading.Tasks.Task<string[]> GetStationsAsync(string ville) {
            return base.Channel.GetStationsAsync(ville);
        }
        
        public string GetNbVelib(string station) {
            return base.Channel.GetNbVelib(station);
        }
        
        public System.Threading.Tasks.Task<string> GetNbVelibAsync(string station) {
            return base.Channel.GetNbVelibAsync(station);
        }
        
        public string[] GetNbVelibInStations(string stationsName) {
            return base.Channel.GetNbVelibInStations(stationsName);
        }
        
        public System.Threading.Tasks.Task<string[]> GetNbVelibInStationsAsync(string stationsName) {
            return base.Channel.GetNbVelibInStationsAsync(stationsName);
        }
    }
}
